"""
Data loader for the marketplace MCP server.

Fetches the markdown catalog from `explore-BBs/bb-catalog/` in the main
building-blocks repo, parses YAML frontmatter, validates with pydantic, and
caches the assembled registry in memory with a TTL.

Produces the same Python dict structures v1's `registry.py` exports
(CORE_CAPABILITIES, GROUPS, BUILDING_BLOCKS, DOCS_PAGES) so the existing
query tools work unchanged — the only swap is markdown-driven vs hardcoded.

Two source modes
----------------
- **GitHub (default)**: fetch live via the GitHub raw + Tree API. The catalog
  is read from the main repo on each cache miss. Content updates ship by PR.
- **Local (testing)**: if env var `BB_CATALOG_LOCAL_PATH` is set, read the
  catalog from that directory on disk. Lets you iterate on schema and content
  without pushing to GitHub. Bypasses the cache (always re-reads from disk).

Public API
----------
    load_registry(force=False) -> dict
    invalidate() -> None

Both are thread-safe.
"""

from __future__ import annotations

import logging
import os
import threading
import time
from pathlib import Path
from typing import Any

import frontmatter
from pydantic import BaseModel, Field, ValidationError

from .github_client import (
    DEFAULT_BRANCH,
    DOCS_REPO_NAME,
    REPO_NAME,
    REPO_OWNER,
    fetch_raw_file,
    fetch_tree,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths and constants
# ---------------------------------------------------------------------------

CATALOG_PATH = "explore-BBs/bb-catalog"
BLOCKS_DIR = f"{CATALOG_PATH}/blocks"

# Re-exported so tools don't need to import github_client directly
REPO_BASE_URL = f"https://github.com/{REPO_OWNER}/{REPO_NAME}"
DOCS_SITE_URL = "https://ibm-self-serve-assets.github.io/building-blocks-docs"

LOADER_TTL_SECONDS = 300  # 5 minutes — see plan: "5-min cache means..."

LOCAL_PATH_ENV = "BB_CATALOG_LOCAL_PATH"

# Last-known-good catalog bundled with the deployment. Used only when a
# cold start cannot reach GitHub AND there is no in-memory cache to serve —
# stale data with a loud warning beats an empty catalog. Refresh it before
# deploys with:  python -m building_blocks_mcp_remote.data_loader --write-snapshot
SNAPSHOT_PATH = Path(__file__).resolve().parent / "fallback_registry.json"


# ---------------------------------------------------------------------------
# Pydantic schemas — validation only, not the wire shape
# ---------------------------------------------------------------------------


class BlockBobMode(BaseModel):
    name: str
    type: str


class BlockSchema(BaseModel):
    id: str
    name: str
    group: str
    capability: str
    description: str
    repo_path: str
    docs_path: str
    products: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    bob_modes: list[BlockBobMode] = Field(default_factory=list)


class CapabilitySchema(BaseModel):
    id: str
    name: str
    description: str


class GroupSchema(BaseModel):
    id: str
    name: str
    capability: str
    description: str


class DocsPageSchema(BaseModel):
    title: str
    section: str
    path: str


class SkillSourceRef(BaseModel):
    location: str          # "block" | "central"
    path: str              # repo-relative path (zip file or directory)
    layout: str            # "bob" | "bare" | "skills" | "dir"


class SkillSchema(BaseModel):
    """One Bob skill from the generated skills catalog (bb-catalog/skills/).

    Generated by explore-BBs/bb-catalog/scripts/sync_skills.py in the
    building-blocks repo — see skills-inventory.md there for provenance.
    """
    id: str
    name: str
    description: str
    blocks: list[str] = Field(default_factory=list)
    status: str = "active"          # "active" | "divergent"
    sources: list[SkillSourceRef] = Field(default_factory=list)
    subskills: list[str] = Field(default_factory=list)
    download: str | None = None
    archive_from: str | None = None


# ---------------------------------------------------------------------------
# Source abstraction: GitHub vs local disk
# ---------------------------------------------------------------------------


def _local_root() -> Path | None:
    """Return the local catalog root if BB_CATALOG_LOCAL_PATH is set, else None."""
    value = os.environ.get(LOCAL_PATH_ENV)
    if not value:
        return None
    root = Path(value).expanduser().resolve()
    if not root.is_dir():
        raise FileNotFoundError(
            f"{LOCAL_PATH_ENV}={value} is set but is not an existing directory"
        )
    return root


def _list_markdown_paths(subdir: str) -> list[str]:
    """List relative markdown paths under {CATALOG_PATH}/{subdir} (e.g. 'blocks')."""
    local = _local_root()
    if local is not None:
        dir_path = local / subdir
        if not dir_path.is_dir():
            return []
        return sorted(f"{subdir}/{p.name}" for p in dir_path.iterdir() if p.suffix == ".md")
    prefix = f"{CATALOG_PATH}/{subdir}/"
    tree = fetch_tree()
    return sorted(
        item["path"][len(CATALOG_PATH) + 1 :]
        for item in tree
        if item.get("type") == "blob"
        and item.get("path", "").startswith(prefix)
        and item["path"].endswith(".md")
    )


def _read_markdown(relative_path: str) -> str:
    """Read a markdown file by path relative to the catalog root."""
    local = _local_root()
    if local is not None:
        return (local / relative_path).read_text(encoding="utf-8")
    return fetch_raw_file(f"{CATALOG_PATH}/{relative_path}")


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _index_by_id(items: list[dict]) -> dict[str, dict]:
    """Convert [{id: 'x', ...}] into {'x': {...}} (id removed from inner dict)."""
    return {item["id"]: {k: v for k, v in item.items() if k != "id"} for item in items}


def _parse_list_file(filename: str, top_key: str, schema: type[BaseModel]) -> list[dict]:
    """Parse a list-style file (capabilities.md / groups.md / docs-pages.md)."""
    content = _read_markdown(filename)
    meta = frontmatter.loads(content)
    raw_items = meta.metadata.get(top_key, [])
    validated: list[dict] = []
    for item in raw_items:
        try:
            validated.append(schema(**item).model_dump())
        except ValidationError as exc:
            logger.error("Schema violation in %s entry %r: %s", filename, item, exc)
            raise
    return validated


def _parse_block_files() -> dict[str, dict]:
    blocks: dict[str, dict] = {}
    for rel_path in _list_markdown_paths("blocks"):
        content = _read_markdown(rel_path)
        meta = frontmatter.loads(content)
        try:
            validated = BlockSchema(**meta.metadata)
        except ValidationError as exc:
            logger.error("Schema violation in %s: %s", rel_path, exc)
            raise
        data = validated.model_dump()
        block_id = data.pop("id")
        blocks[block_id] = data
    return blocks


def _parse_skill_files() -> dict[str, dict]:
    """Parse the generated skills catalog (skills/*.md). Absence is not an
    error — an older catalog checkout may predate the skills layer."""
    skills: dict[str, dict] = {}
    for rel_path in _list_markdown_paths("skills"):
        content = _read_markdown(rel_path)
        meta = frontmatter.loads(content)
        try:
            validated = SkillSchema(**meta.metadata)
        except ValidationError as exc:
            logger.error("Schema violation in %s: %s", rel_path, exc)
            raise
        data = validated.model_dump()
        skill_id = data.pop("id")
        skills[skill_id] = data
    return skills


def _build_registry() -> dict[str, Any]:
    """Fetch and parse the full catalog. Returns the assembled registry dicts."""
    source = "local disk" if _local_root() else "GitHub"
    logger.info("Loading catalog from %s...", source)
    capabilities = _parse_list_file("capabilities.md", "capabilities", CapabilitySchema)
    groups = _parse_list_file("groups.md", "groups", GroupSchema)
    docs_pages = _parse_list_file("docs-pages.md", "pages", DocsPageSchema)
    blocks = _parse_block_files()
    skills = _parse_skill_files()
    logger.info(
        "Loaded %d capabilities, %d groups, %d blocks, %d docs pages, %d skills",
        len(capabilities),
        len(groups),
        len(blocks),
        len(docs_pages),
        len(skills),
    )
    return {
        "CORE_CAPABILITIES": _index_by_id(capabilities),
        "GROUPS": _index_by_id(groups),
        "BUILDING_BLOCKS": blocks,
        "DOCS_PAGES": docs_pages,
        "SKILLS": skills,
    }


def _load_snapshot() -> dict[str, Any]:
    import json

    with open(SNAPSHOT_PATH, encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------------------
# Cache and public API
# ---------------------------------------------------------------------------

_lock = threading.Lock()
_cache: dict[str, Any] = {}
_cache_ts: float = 0.0


def load_registry(force: bool = False) -> dict[str, Any]:
    """Return the parsed catalog, fetching from source if cache is stale.

    Thread-safe. In local-disk mode the cache is bypassed so edits are picked up
    immediately (TTL-based caching only applies to GitHub fetches).
    """
    global _cache, _cache_ts
    if _local_root() is not None:
        # Local development: always re-read so file edits show up instantly.
        return _build_registry()

    with _lock:
        fresh = _cache and (time.monotonic() - _cache_ts) < LOADER_TTL_SECONDS
        if not force and fresh:
            return _cache
        try:
            _cache = _build_registry()
            _cache_ts = time.monotonic()
            return _cache
        except Exception as exc:
            # Degrade gracefully: stale in-memory cache first, then the
            # bundled snapshot. A cold start with GitHub unreachable must
            # never leave the server with no catalog at all.
            if _cache:
                logger.error(
                    "Catalog refresh failed (%s) — serving STALE cached catalog", exc
                )
                return _cache
            if SNAPSHOT_PATH.is_file():
                logger.error(
                    "Catalog fetch failed on cold start (%s) — serving bundled "
                    "FALLBACK SNAPSHOT; data may be outdated", exc
                )
                _cache = _load_snapshot()
                _cache_ts = 0.0  # never counts as fresh; retry upstream next call
                return _cache
            raise


def invalidate() -> None:
    """Force the next load_registry() call to re-fetch from source."""
    global _cache, _cache_ts
    with _lock:
        _cache = {}
        _cache_ts = 0.0
    logger.info("Catalog cache invalidated")


# ---------------------------------------------------------------------------
# CLI entry point: sanity-check the loader against local or GitHub source
# ---------------------------------------------------------------------------


def _cli() -> None:
    import argparse
    import json

    parser = argparse.ArgumentParser(
        description="Sanity-check the data loader. Set BB_CATALOG_LOCAL_PATH to use local files; otherwise fetches from GitHub.",
    )
    parser.add_argument("--dump", action="store_true", help="Print full registry as JSON")
    parser.add_argument("--block", help="Print one block by id")
    parser.add_argument("--write-snapshot", action="store_true",
                        help=f"Write the loaded registry to {SNAPSHOT_PATH.name} "
                             "(the cold-start fallback bundled with deploys)")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    reg = load_registry()

    if args.write_snapshot:
        import json

        SNAPSHOT_PATH.write_text(json.dumps(reg, indent=1, sort_keys=True), encoding="utf-8")
        print(f"Snapshot written: {SNAPSHOT_PATH} ({SNAPSHOT_PATH.stat().st_size:,} bytes)")
        return

    if args.block:
        print(json.dumps(reg["BUILDING_BLOCKS"].get(args.block, {}), indent=2))
        return
    if args.dump:
        print(json.dumps({k: v for k, v in reg.items()}, indent=2, default=str))
        return

    # Default: counts
    print(f"capabilities : {len(reg['CORE_CAPABILITIES'])}")
    print(f"groups       : {len(reg['GROUPS'])}")
    print(f"blocks       : {len(reg['BUILDING_BLOCKS'])}")
    print(f"docs pages   : {len(reg['DOCS_PAGES'])}")


if __name__ == "__main__":
    _cli()
