#!/usr/bin/env python3
"""
Skills catalog generator for explore-BBs/bb-catalog/skills/.

Scans the two places Bob skills live in this repository —

  1. Per-block:  */bob-skills/**/*.zip   (three internal zip layouts)
  2. Central:    ibm-bob/skills/<name>/  (unpacked directories)

— extracts each skill's SKILL.md metadata, reconciles duplicates and aliases
by CONTENT (never by name alone: name fields are known to carry copy-paste
errors), and emits:

  - bb-catalog/skills/<id>.md      one file per active skill (frontmatter)
  - bb-catalog/skills-inventory.md human-readable report of everything found,
                                   including divergences, exclusions, aliases,
                                   and skills with no owning block

Anything abnormal (divergent copies, unparseable zips, unknown layouts) is
surfaced in the report — a malformed skill can never corrupt the catalog,
only fail to enter it.

Read-only outside explore-BBs/: the scan reads other teams' folders but all
output lands under explore-BBs/bb-catalog/.

Corrections for known-bad upstream metadata live in overrides.yaml next to
this script (aliases, exclusions, display-name fixes, block assignments).
Never edit other teams' skill files to fix metadata — add an override.

Usage:
    python3 explore-BBs/bb-catalog/scripts/sync_skills.py           # regenerate
    python3 explore-BBs/bb-catalog/scripts/sync_skills.py --check   # CI: exit 1 if
                                                                    # committed output is stale

Requires: PyYAML.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import re
import sys
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

import yaml

SCRIPTS_DIR = Path(__file__).resolve().parent
CATALOG_DIR = SCRIPTS_DIR.parent                  # explore-BBs/bb-catalog
REPO_ROOT = CATALOG_DIR.parents[1]                # repository root
SKILLS_OUT_DIR = CATALOG_DIR / "skills"
ARCHIVES_DIR = CATALOG_DIR / "skill-archives"     # generated zips for zip-less skills
ARCHIVES_REL = "explore-BBs/bb-catalog/skill-archives"
INVENTORY_PATH = CATALOG_DIR / "skills-inventory.md"
OVERRIDES_PATH = SCRIPTS_DIR / "overrides.yaml"

RAW_BASE = "https://raw.githubusercontent.com/ibm-self-serve-assets/building-blocks/main"
CENTRAL_PREFIX = "ibm-bob/skills"

# When a skill exists in more than one source, which location backs the
# download URL. "block" = per-BB bob-skills zip; "central" = ibm-bob/skills.
PRIMARY_SOURCE = "block"

GENERATED_HEADER = "<!-- GENERATED by sync_skills.py — do not edit by hand. Fix upstream or add an override in scripts/overrides.yaml. -->"


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class SkillSource:
    """One place a skill's bytes were found."""
    location: str          # "block" | "central"
    path: str              # repo-relative path (zip file or directory)
    inner_name: str        # directory name of the skill inside the source
    layout: str            # "bob" (.bob/skills/<n>/), "bare", "skills", "dir"
    name: str              # SKILL.md frontmatter `name:` (as found, uncorrected)
    description: str       # SKILL.md frontmatter `description:`
    content_hash: str      # hash of the FULL payload (all files; see _payload_hash)
    has_top: bool          # True if a SKILL.md exists at the skill's root
    subskills: list = field(default_factory=list)  # nested SKILL.md dirs
    anomalies: list = field(default_factory=list)  # junk files, oddities


# ---------------------------------------------------------------------------
# SKILL.md parsing
# ---------------------------------------------------------------------------

def _parse_skill_md(text: str, origin: str) -> tuple[str, str]:
    """Return (name, description) from a SKILL.md's frontmatter."""
    if not text.startswith("---"):
        raise ValueError(f"{origin}: SKILL.md has no frontmatter")
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"{origin}: SKILL.md frontmatter unterminated")
    fm = yaml.safe_load(parts[1]) or {}
    name = str(fm.get("name", "")).strip()
    desc = " ".join(str(fm.get("description", "")).split())
    if not name:
        raise ValueError(f"{origin}: SKILL.md missing `name:`")
    return name, desc


def _norm_skill_md(data: bytes) -> bytes:
    """Normalize a SKILL.md for hashing: drop the frontmatter `name:` line
    and trailing whitespace, so the same skill published under two names (a
    known aliasing pattern) still hashes identically."""
    text = data.decode("utf-8", errors="replace")
    lines = [ln.rstrip() for ln in text.splitlines() if not re.match(r"^name:\s", ln)]
    return "\n".join(lines).strip().encode("utf-8")


def _payload_hash(files: list[tuple[str, bytes]]) -> str:
    """Hash of the full skill payload — every file, not just SKILL.md.

    Divergence between two copies of a skill often lives in knowledge/example
    files while SKILL.md matches (verified for maximo-code-optimization), so
    the whole tree participates. SKILL.md files are name-line-normalized.
    """
    h = hashlib.sha256()
    for rel, data in sorted(files):
        if rel.endswith("SKILL.md"):
            data = _norm_skill_md(data)
        h.update(rel.encode("utf-8"))
        h.update(b"\0")
        h.update(hashlib.sha256(data).digest())
    return h.hexdigest()[:16]


# ---------------------------------------------------------------------------
# Source scanners
# ---------------------------------------------------------------------------

_JUNK = ("__MACOSX/", ".DS_Store")


def _scan_zip(zip_path: Path) -> SkillSource:
    """Extract skill metadata from one bob-skills zip (any of the 3 layouts)."""
    rel = str(zip_path.relative_to(REPO_ROOT))
    with zipfile.ZipFile(zip_path) as zf:
        names = [n for n in zf.namelist() if not any(j in n for j in _JUNK)]
        junk = [n for n in zf.namelist() if any(j in n for j in _JUNK)]

        skill_mds = sorted(
            (n for n in names if n.endswith("SKILL.md")), key=lambda n: (n.count("/"), n)
        )
        if not skill_mds:
            raise ValueError(f"{rel}: no SKILL.md anywhere in zip")

        # Layout-agnostic root: the common ancestor directory of every
        # SKILL.md in the zip. Handles all observed layouts — .bob/skills/
        # -prefixed, skills/-wrapped, bare, wrapper-around-skills/ (e.g.
        # vault-secret-migrator/skills/<name>/), and composite zips whose
        # sub-skills share a parent.
        import posixpath
        dirs = [posixpath.dirname(n) for n in skill_mds]
        root_dir = dirs[0]
        for d in dirs[1:]:
            root_dir = posixpath.commonpath([root_dir, d])
        # If the common ancestor IS a structural wrapper folder (a zip
        # carrying multiple skills under skills/ or .bob/skills/), step up
        # to the wrapper that names the skill (composite zips, e.g.
        # automated-resource-mgmt-turbonomic/skills/{backend,frontend,...}).
        while root_dir and posixpath.basename(root_dir) in ("skills", ".bob"):
            root_dir = posixpath.dirname(root_dir)
        if not root_dir:
            raise ValueError(f"{rel}: multiple top-level skills in one zip — unsupported")
        inner = posixpath.basename(root_dir)
        root = root_dir + "/"
        rparts = root_dir.split("/")
        if rparts[:2] == [".bob", "skills"]:
            layout = "bob"
        elif rparts[0] == "skills":
            layout = "skills"
        elif "skills" in rparts:
            layout = "nested"
        else:
            layout = "bare"

        # Metadata comes from the skill-root SKILL.md if there is one; some
        # composite zips ship only sub-skill SKILL.mds (no root), in which
        # case the id doubles as the name and there is no description here.
        top = f"{root}SKILL.md"
        has_top = top in names
        anomalies = [f"zip contains junk entries ({len(junk)})"] if junk else []
        if has_top:
            name, desc = _parse_skill_md(
                zf.read(top).decode("utf-8", errors="replace"), rel
            )
        else:
            name, desc = inner, ""
            anomalies.append("no root SKILL.md (composite zip; metadata from another source if available)")

        subskills = sorted(
            n[len(root):].rsplit("/", 2)[-2]
            for n in skill_mds
            if n != top and n.startswith(root)
        )
        payload = [
            (n[len(root):], zf.read(n)) for n in names
            if n.startswith(root) and not n.endswith("/")
        ]

    return SkillSource(
        location="block", path=rel, inner_name=inner, layout=layout,
        name=name, description=desc, content_hash=_payload_hash(payload),
        has_top=has_top, subskills=subskills, anomalies=anomalies,
    )


def _scan_central_dir(dir_path: Path) -> SkillSource:
    """Extract skill metadata from one unpacked ibm-bob/skills/<name>/ dir."""
    rel = str(dir_path.relative_to(REPO_ROOT))
    skill_md = dir_path / "SKILL.md"
    if not skill_md.is_file():
        raise ValueError(f"{rel}: directory has no top-level SKILL.md")
    text = skill_md.read_text(encoding="utf-8")
    name, desc = _parse_skill_md(text, rel)
    subskills = sorted(
        p.parent.name for p in dir_path.rglob("SKILL.md") if p != skill_md
    )
    payload = [
        (str(p.relative_to(dir_path)), p.read_bytes())
        for p in sorted(dir_path.rglob("*"))
        if p.is_file() and not any(j.strip("/") in p.parts for j in _JUNK)
    ]
    return SkillSource(
        location="central", path=rel, inner_name=dir_path.name, layout="dir",
        name=name, description=desc, content_hash=_payload_hash(payload),
        has_top=True, subskills=subskills,
    )


def _load_block_paths() -> dict[str, str]:
    """block_id -> repo_path from the blocks catalog."""
    blocks = {}
    for p in sorted((CATALOG_DIR / "blocks").glob("*.md")):
        fm = yaml.safe_load(p.read_text(encoding="utf-8").split("---", 2)[1])
        blocks[fm["id"]] = fm["repo_path"]
    return blocks


def _owning_block(source_path: str, blocks: dict[str, str]) -> str | None:
    """Longest repo_path prefix match wins."""
    best, best_len = None, -1
    for bid, rp in blocks.items():
        if (source_path == rp or source_path.startswith(rp + "/")) and len(rp) > best_len:
            best, best_len = bid, len(rp)
    return best


# ---------------------------------------------------------------------------
# Reconciliation
# ---------------------------------------------------------------------------

def collect_sources(errors: list[str]) -> list[SkillSource]:
    sources: list[SkillSource] = []
    # Any-depth scan: bob-skills/ folders nest up to 4+ levels deep
    # (e.g. data/retrieval/vector-search/opensearch/bob-skills/). Fixed
    # depth patterns silently missed the deepest ones.
    for zp in sorted(
        p for p in REPO_ROOT.glob("**/bob-skills/**/*.zip")
        if ".git" not in p.parts and "explore-BBs" not in p.parts
    ):
        try:
            sources.append(_scan_zip(zp))
        except Exception as exc:
            errors.append(str(exc))
    central = REPO_ROOT / CENTRAL_PREFIX
    for d in sorted(p for p in central.iterdir() if p.is_dir()):
        try:
            sources.append(_scan_central_dir(d))
        except Exception as exc:
            errors.append(str(exc))
    return sources


def reconcile(
    sources: list[SkillSource], overrides: dict, blocks: dict[str, str]
) -> tuple[list[dict], dict]:
    """Group sources into skills; return (skills, report_sections)."""
    aliases: dict = overrides.get("aliases") or {}
    excludes: set = set(overrides.get("exclude") or [])
    name_fixes: dict = overrides.get("names") or {}
    block_fixes: dict = overrides.get("blocks") or {}

    groups: dict[str, list[SkillSource]] = {}
    excluded, alias_notes = [], []
    for s in sources:
        cid = aliases.get(s.inner_name, s.inner_name)
        if cid != s.inner_name:
            alias_notes.append(f"`{s.inner_name}` ({s.path}) → canonical id `{cid}`")
        if s.inner_name in excludes or cid in excludes:
            excluded.append(s)
            continue
        groups.setdefault(cid, []).append(s)

    skills, divergent_notes, name_fix_notes = [], [], []
    for cid in sorted(groups):
        grp = groups[cid]
        hashes = {s.content_hash for s in grp}
        # Deterministic primary: preferred location first, then path order.
        primary = sorted(
            grp, key=lambda s: (s.location != PRIMARY_SOURCE, s.path)
        )[0]

        status = "active"
        if len(hashes) > 1:
            status = "divergent"
            detail = ", ".join(f"{s.path} [{s.content_hash}]" for s in grp)
            divergent_notes.append(
                f"`{cid}`: {len(grp)} copies with {len(hashes)} distinct contents — "
                f"serving {primary.path}. Copies: {detail}"
            )

        # Name/description come from a source with a root SKILL.md; some
        # composite zips lack one, in which case another copy supplies it.
        meta = next(
            (s for s in sorted(grp, key=lambda s: (s.location != PRIMARY_SOURCE, s.path))
             if s.has_top),
            primary,
        )
        display_name = name_fixes.get(cid, meta.name)
        if cid in name_fixes:
            name_fix_notes.append(
                f"`{cid}`: SKILL.md says name `{meta.name}` — corrected to `{display_name}`"
            )
        elif meta.name != cid:
            name_fix_notes.append(
                f"`{cid}`: SKILL.md name field is `{meta.name}` (differs from id; "
                f"no override set — using SKILL.md value)"
            )
            display_name = meta.name

        owning = sorted({
            b for s in grp
            if s.location == "block" and (b := _owning_block(s.path, blocks))
        })
        if cid in block_fixes:
            owning = sorted(block_fixes[cid])

        download = None
        archive_from = None
        if primary.path.endswith(".zip"):
            download = f"{RAW_BASE}/{primary.path}"
        else:
            zips = [s for s in grp if s.path.endswith(".zip")]
            if zips:
                download = f"{RAW_BASE}/{zips[0].path}"
            else:
                # No zip anywhere upstream — we archive the unpacked source
                # ourselves into skill-archives/ (built deterministically below).
                download = f"{RAW_BASE}/{ARCHIVES_REL}/{cid}.zip"
                archive_from = primary.path

        skills.append({
            "id": cid,
            "name": display_name,
            "description": meta.description,
            "blocks": owning,
            "status": status,
            "sources": [
                {"location": s.location, "path": s.path, "layout": s.layout}
                for s in sorted(grp, key=lambda s: (s.location, s.path))
            ],
            "subskills": meta.subskills,
            "download": download,
            **({"archive_from": archive_from} if archive_from else {}),
        })

    report = {
        "excluded": [f"`{s.inner_name}` ({s.path})" for s in excluded],
        "aliases": sorted(set(alias_notes)),
        "divergent": divergent_notes,
        "name_fixes": name_fix_notes,
    }
    return skills, report


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def build_archive(source_dir: Path, inner: str) -> bytes:
    """Deterministic zip of an unpacked skill dir (bare layout: <inner>/...).

    Byte-stable across runs and platforms: fixed 1980 timestamps, sorted
    entries, STORED (no compression — deflate output varies by zlib build).
    Stability matters because --check compares committed archives by content.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_STORED) as zf:
        for p in sorted(source_dir.rglob("*")):
            if not p.is_file() or any(j.strip("/") in p.parts for j in _JUNK):
                continue
            info = zipfile.ZipInfo(
                f"{inner}/{p.relative_to(source_dir)}", date_time=(1980, 1, 1, 0, 0, 0)
            )
            info.external_attr = 0o644 << 16
            zf.writestr(info, p.read_bytes())
    return buf.getvalue()


def render_skill_md(skill: dict) -> str:
    fm = yaml.safe_dump(skill, sort_keys=False, allow_unicode=True, width=100).strip()
    body = (
        f"# {skill['name']}\n\n{skill['description']}\n\n"
        f"Sources in this repo:\n"
        + "\n".join(f"- `{s['path']}` ({s['location']}, layout: {s['layout']})"
                    for s in skill["sources"])
        + "\n"
    )
    return f"---\n{fm}\n---\n{GENERATED_HEADER}\n\n{body}"


def render_inventory(skills: list[dict], report: dict, errors: list[str]) -> str:
    active = [s for s in skills if s["status"] == "active"]
    divergent = [s for s in skills if s["status"] == "divergent"]
    unowned = [s for s in skills if not s["blocks"]]

    lines = [
        "# Bob Skills Inventory",
        "",
        GENERATED_HEADER,
        "",
        f"**{len(skills)} skills** in the catalog "
        f"({len(active)} clean, {len(divergent)} divergent) · "
        f"{len(unowned)} without an owning block · "
        f"{len(report['excluded'])} excluded · {len(errors)} scan errors",
        "",
        "| Skill | Blocks | Status | Sources | Download |",
        "|---|---|---|---|---|",
    ]
    for s in skills:
        blocks = ", ".join(s["blocks"]) or "—"
        srcs = ", ".join(f"{x['location']}" for x in s["sources"])
        dl = "zip (generated)" if s.get("archive_from") else ("zip" if s["download"] else "**none**")
        lines.append(f"| `{s['id']}` | {blocks} | {s['status']} | {srcs} | {dl} |")

    def section(title: str, items: list[str], empty: str) -> None:
        lines.extend(["", f"## {title}", ""])
        lines.extend(f"- {i}" for i in items) if items else lines.append(f"_{empty}_")

    section("Divergent copies (same skill, different content — needs owner decision)",
            report["divergent"], "None")
    section("Skills without an owning block (block missing from catalog, or cross-cutting)",
            [f"`{s['id']}` — sources: " + ", ".join(x["path"] for x in s["sources"])
             for s in unowned], "None")
    section("Generated archives (zip-less upstream sources, zipped into skill-archives/)",
            [f"`{s['id']}` ← {s['archive_from']}" for s in skills if s.get("archive_from")],
            "None")
    section("Excluded by override", report["excluded"], "None")
    section("Aliases applied", report["aliases"], "None")
    section("Name-field corrections / mismatches", report["name_fixes"], "None")
    section("Scan errors (sources that could not be parsed)", errors, "None")
    lines.append("")
    return "\n".join(lines)


def generate() -> tuple[dict[str, str], dict[str, bytes], str]:
    """Return ({skill filename -> content}, {archive filename -> bytes}, inventory)."""
    errors: list[str] = []
    overrides = {}
    if OVERRIDES_PATH.is_file():
        overrides = yaml.safe_load(OVERRIDES_PATH.read_text(encoding="utf-8")) or {}
    blocks = _load_block_paths()
    sources = collect_sources(errors)
    skills, report = reconcile(sources, overrides, blocks)
    files = {f"{s['id']}.md": render_skill_md(s) for s in skills}
    archives = {
        f"{s['id']}.zip": build_archive(REPO_ROOT / s["archive_from"], s["id"])
        for s in skills if s.get("archive_from")
    }
    inventory = render_inventory(skills, report, errors)
    return files, archives, inventory


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if committed output differs from a fresh run (CI staleness gate)")
    args = parser.parse_args()

    files, archives, inventory = generate()

    if args.check:
        stale = []
        current = {p.name: p.read_text(encoding="utf-8")
                   for p in SKILLS_OUT_DIR.glob("*.md")} if SKILLS_OUT_DIR.is_dir() else {}
        for name, content in files.items():
            if current.get(name) != content:
                stale.append(f"skills/{name}")
        stale += [f"skills/{n} (orphaned)" for n in current if n not in files]
        cur_zips = {p.name: p.read_bytes()
                    for p in ARCHIVES_DIR.glob("*.zip")} if ARCHIVES_DIR.is_dir() else {}
        for name, data in archives.items():
            if cur_zips.get(name) != data:
                stale.append(f"skill-archives/{name}")
        stale += [f"skill-archives/{n} (orphaned)" for n in cur_zips if n not in archives]
        if INVENTORY_PATH.is_file():
            if INVENTORY_PATH.read_text(encoding="utf-8") != inventory:
                stale.append("skills-inventory.md")
        else:
            stale.append("skills-inventory.md (missing)")
        if stale:
            print("STALE — committed skills catalog differs from a fresh generation:")
            for s in stale:
                print(f"  - {s}")
            print("\nRun: python3 explore-BBs/bb-catalog/scripts/sync_skills.py")
            return 1
        print(f"UP TO DATE — {len(files)} skills, {len(archives)} archives, inventory current.")
        return 0

    SKILLS_OUT_DIR.mkdir(exist_ok=True)
    for existing in SKILLS_OUT_DIR.glob("*.md"):
        if existing.name not in files:
            existing.unlink()
            print(f"removed {existing.name}")
    for name, content in sorted(files.items()):
        (SKILLS_OUT_DIR / name).write_text(content, encoding="utf-8")
    ARCHIVES_DIR.mkdir(exist_ok=True)
    for existing in ARCHIVES_DIR.glob("*.zip"):
        if existing.name not in archives:
            existing.unlink()
            print(f"removed skill-archives/{existing.name}")
    for name, data in sorted(archives.items()):
        (ARCHIVES_DIR / name).write_bytes(data)
    INVENTORY_PATH.write_text(inventory, encoding="utf-8")
    print(f"Wrote {len(files)} skills, {len(archives)} archives, and {INVENTORY_PATH.name}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
